name = "gliana-pay-web-dev"
compatibility_date = "2026-02-21"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".svelte-kit/cloudflare"

[[services]]
binding = "GLIANA_PAY_WORKER"
service = "gliana-pay-worker-dev"
